- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: r_os_servers

- name: Create in-memory inventory
  add_host:
    name: "{{ item.public_v4 }}"
    groups: "{{ item.metadata.group }}"
#    groups: "{{ item.metadata.deployment_name }}"
  loop: "{{ r_os_servers.ansible_facts.openstack_servers }}"